[package]
name = "keen"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.13"
chumsky = "0.9"
cranelift = "0.102"
cranelift-jit = "0.102"
cranelift-module = "0.102"
cranelift-object = "0.102"
cranelift-native = "0.102"
target-lexicon = "0.12"
